version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: wordpress-nginx
    ports:
      - "8088:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - app-network

  php:
    image: lgolabek/wp-image:1.0
    container_name: wordpress-php
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

  mysql:
    image: mysql:latest
    container_name: wordpress-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    volumes:
      - ./docker/db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
